### ISSUE TITLE
Error when installing AD-Miner

### ISSUE THREAD

**Issue by obiwan420** [Mazars-Tech/AD_Miner#184] opened 2024-09-18 20:17 UTC
**Describe the bug**
Error when installing AD-Miner

**Terminal Output**
─$ pipx install 'git+https://github.com/Mazars-Tech/AD_Miner.git'
Fatal error from pip prevented installation. Full pip output in file:
    /home/itsa/.local/state/pipx/log/cmd_2024-09-18_13.12.38_pip_errors.log

pip seemed to fail to build package:
    neo4j==5.6.0

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

Error installing AD_Miner from spec 'git+https://github.com/Mazars-Tech/AD_Miner.git'.
                                                                                           

**System information**
 - Kali 2024.4

**Comment by obiwan420** [comment] 2024-09-18 20:24
Correction Kali 2024.3

**Comment by obiwan420** [comment] 2024-09-18 20:52
I was able to reproduce the error on a fresh install of Kali 2024.3 after running updates.

**Comment by jmbesnard** [comment] 2024-09-19 07:32
Hi,

You might want to try python -m pip install --upgrade pip setuptools

**Comment by obiwan420** [comment] 2024-09-19 14:51
Same results. I did have to use --break-system-packages to run the recommend command line

─$ python -m pip install --upgrade pip setuptools --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (24.2)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (70.3.0)
Collecting setuptools
  Downloading setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
Downloading setuptools-75.1.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 12.3 MB/s eta 0:00:00
Installing collected packages: setuptools
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
theharvester 4.6.0 requires aiodns==3.1.1, but you have aiodns 3.2.0 which is incompatible.                                                                                    
theharvester 4.6.0 requires aiofiles==23.2.1, but you have aiofiles 24.1.0 which is incompatible.                                                                              
theharvester 4.6.0 requires aiohttp==3.9.3, but you have aiohttp 3.10.5 which is incompatible.                                                                                 
theharvester 4.6.0 requires censys==2.2.11, but you have censys 2.2.13 which is incompatible.                                                                                  
theharvester 4.6.0 requires certifi==2024.2.2, but you have certifi 2024.8.30 which is incompatible.                                                                           
theharvester 4.6.0 requires lxml==5.1.0, but you have lxml 5.3.0 which is incompatible.                                                                                        
theharvester 4.6.0 requires netaddr==1.2.1, but you have netaddr 0.10.1 which is incompatible.                                                                                 
theharvester 4.6.0 requires playwright==1.42.0, but you have playwright 0.0.0 which is incompatible.                                                                           
theharvester 4.6.0 requires python-dateutil==2.9.0.post0, but you have python-dateutil 2.9.0 which is incompatible.                                                            
theharvester 4.6.0 requires PyYAML==6.0.1, but you have pyyaml 6.0.2 which is incompatible.                                                                                    
theharvester 4.6.0 requires requests==2.31.0, but you have requests 2.32.3 which is incompatible.                                                                              
theharvester 4.6.0 requires retrying==1.3.4, but you have retrying 1.3.3 which is incompatible.                                                                                
theharvester 4.6.0 requires setuptools==69.2.0, but you have setuptools 75.1.0 which is incompatible.                                                                          
theharvester 4.6.0 requires slowapi==0.1.9, but you have slowapi 0.1.4 which is incompatible.                                                                                  
theharvester 4.6.0 requires ujson==5.9.0, but you have ujson 5.10.0 which is incompatible.                                                                                     
theharvester 4.6.0 requires uvicorn==0.28.0, but you have uvicorn 0.30.6 which is incompatible.                                                                                
theharvester 4.6.0 requires uvloop==0.19.0; platform_system != "Windows", but you have uvloop 0.20.0 which is incompatible.                                                    
Successfully installed setuptools-75.1.0                                                                                                                                       
                                                                                                                                                                               
┌──(㉿kali)-[~]
└─$ pipx install 'git+https://github.com/Mazars-Tech/AD_Miner.git'
Fatal error from pip prevented installation. Full pip output in file:
    /home/itsa/.local/state/pipx/log/cmd_2024-09-19_07.47.58_pip_errors.log

pip seemed to fail to build package:
    neo4j==5.6.0

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

Error installing AD_Miner from spec 'git+https://github.com/Mazars-Tech/AD_Miner.git'.
                                                                                                                                                                               
┌──(㉿kali)-[~]
└─$

**Comment by L1-0** [comment] 2024-09-23 07:53
Same Issue over here, i guess the problem is the upgraded python installation. 3.12 removed support for 'pkgutil' so this really old requirement for a last years neo4j is causing the problem. Consider downgrading python or upgrading the neo4j requirement through testing.

**Comment by jmbesnard** [comment] 2024-09-23 09:14
Thanks for reporting this. We are working on this issue and will provide a fix to the dev branch today. A new version (including a series of bug fixes) will be issued ASAP.

**Comment by jmbesnard** [comment] 2024-09-24 20:03
Fix is ready and will be part of next version to be released.... "soon"

**Comment by obiwan420** [comment] 2024-10-03 14:51
I was able to install AD-Miner v1.6.0 using a backed-up image that does not have latest python build installed

┌──(㉿kali)-[~]
└─$ pipx install 'git+https://github.com/Mazars-Tech/AD_Miner.git'
  installed package AD_Miner 1.6.0, installed using Python 3.11.9
  These apps are now globally available
    - AD-miner
done! ✨  ✨

**Comment by jmbesnard** [comment] 2024-10-03 20:06
Have you tried the latest version that was released today? It has a fix for this

**Comment by obiwan420** [comment] 2024-10-03 20:25
Worked! Thank you.

**Closed** 2024-10-04 06:47 UTC
Labels: bug
