### ISSUE TITLE
Bug - Split objects into types

### ISSUE THREAD

**Issue by TH3xACE** [Mazars-Tech/AD_Miner#126] opened 2024-02-26 20:02 UTC
[144/145] [+]From cache : Paths between two global admins belonging to different tenants - 0 objects
[145/145] [+]From cache : Paths between tenants admin and domain admins - 0 objects
[+]Requests finished !
[+]Computing domains objects
[+]Generate paths to objects that can GPLink GPOs on OUs
[+]Split objects into types...
Traceback (most recent call last):
  File "/workspace/ctools/AD_Tools/AD_Miner/.venv/bin/AD-miner", line 6, in <module>
    sys.exit(main())
  File "/workspace/ctools/AD_Tools/AD_Miner/ad_miner/__main__.py", line 182, in main
    domains = Domains(arguments, neo4j)
  File "/workspace/ctools/AD_Tools/AD_Miner/ad_miner/sources/modules/domains.py", line 243, in __init__
    self.generatePathToDa()
  File "/workspace/ctools/AD_Tools/AD_Miner/ad_miner/sources/modules/domains.py", line 666, in generatePathToDa
    self.ou_to_domain_admin[path.nodes[-1].domain].append(path)
KeyError: 'ADTEST.ROOT.NET'

**Comment by jmbesnard** [comment] 2024-02-27 14:50
Thanks for sharing this issue. Could you please tell us whether you are using BH legacy or BH CE to ingest the data ?

Also, were the data generated by Sharphound or Rusthound or bloodhound.py ?

Do your data contain on-prem and/or Azure ?

Could you please also run the following cypher (either using cypher-shell or from the neo4j web interface - NOT from the BH cypher prompt):

MATCH (d:Domain) WITH collect(d.domain) AS doms MATCH (n) where NOT n.domain IN doms return n.name
and tell us if this return anything

Thanks

**Comment by snowpeacock** [comment] 2024-02-28 13:30
Hello, thanks for the feedback. Which collector are you using, and which Bloodhound version?

**Comment by TH3xACE** [comment] 2024-02-28 14:31
The tools seems amazing...  and looking forward to be able to test it fully
- BH used:  Legacy
- Collector: rusthound
- Target: on-prem

Returned nothing with the cypher : MATCH (d:Domain) WITH collect(d.domain) AS doms MATCH (n) where NOT n.domain IN doms return n.name

**Comment by TH3xACE** [comment] 2024-03-01 19:42
Thank you I will join the discord. I have used dump not made wih rusthound and works fine. I guess the issue is with rusthound. Do you know what is the issue ? how it works on BH  if the data collected has some issues. I guess it is a known issue ? data collected with Rusthound

**Comment by cmprmsd** [comment] 2024-03-12 10:22
Any updates on this issue? I'm having the same problem :dagger:

**Comment by TH3xACE** [comment] 2024-03-12 10:27
The issue seems to be related to the collected data when using rusthound. Using another collector seems to work.
The issue/bug is  not fixed but is like a workaround despite identifying the issue and correcting it would be great.

@jmbesnard  if you perform two collection from same system using SharpHound and RustHound, does comparing the two collection (json) will not help identifying the issue and could take care of some malformed json or else when collecting with RH ?

**Comment by TH3xACE** [comment] 2024-03-12 10:30
@cmprmsd does the https://github.com/Mazars-Tech/AD_Miner/pull/125 helped to fix the issue ?? works now with RH??

**Comment by cmprmsd** [comment] 2024-03-12 10:31
I cloned the repo ran poetry install and poetry shell, 
confirmed with which ad-miner that it is using the venv but it seems the error persists.

**Comment by cmprmsd** [comment] 2024-03-12 10:41
```
[+]Requests finished !
[+]Computing domains objects
[+]Generate paths to objects that can GPLink GPOs on OUs
[+]Split objects into types...
Traceback (most recent call last):
  File "/data/customer/adminer/AD_Miner/.venv/bin/AD-miner", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/customer/adminer/AD_Miner/ad_miner/__main__.py", line 182, in main
    domains = Domains(arguments, neo4j)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/customer/adminer/AD_Miner/ad_miner/sources/modules/domains.py", line 243, in __init__
    self.generatePathToDa()
  File "/data/customer/adminer/AD_Miner/ad_miner/sources/modules/domains.py", line 666, in generatePathToDa
    self.ou_to_domain_admin[path.nodes[-1].domain].append(path)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'a.b.LOCAL.INT'
```

**Comment by cmprmsd** [comment] 2024-03-12 13:26
@jmbesnard Thanks, but isn't this what I do, when I clone the repo and run the poetry commands from above?

**Comment by jmbesnard** [comment] 2024-03-12 13:39
True, I misread the comment. @TH3xACE I did try that and could not reproduce the problem unfortunately.

**Comment by jmbesnard** [comment] 2024-03-12 13:41
@cmprmsd also feel free to join us on Discord as it may be easier to further discuss the issue

**Comment by jmbesnard** [comment] 2024-04-08 09:10
Not receiving any updates on this issue so closing it.

**Closed by jmbesnard** 2024-04-08 09:10 UTC
Labels: bug

**Comment by noraj** [comment] 2025-10-07 12:44
From neo4j WebUI:

- `MATCH (d:Domain) WITH collect(d.domain) AS doms MATCH (n) where NOT n.domain IN doms return n.name` -> 6496 records.
- `MATCH(n) return distinct n.domain` -> returns all (6) domains
- `MATCH(d:Domain) return d.domain,d.name` -> return only 5 domains where the one missing is the one triggering the KeyError.

**Comment by jmbesnard** [comment] 2025-10-07 13:09
What I meant is that the WEB UI is not adequate for running queries that return neither paths nor nodes. I would strongly suggest using cypher-shell.
If you must stick with the WEB UI, then check if this returns anything (slightly modified cypher):
MATCH (d:Domain) WITH collect(d.domain) AS doms MATCH (n) where NOT n.domain IN doms return n
If you see nodes showing up then you have  nodes for which the domain attributes does not match any existing Domain node. Checking those out might help making sense of why this happens. Either way, deleting these nodes shall fix the issue.
Also, having 2 imports/ingestions is of course not a problem. However, do run AD Miner only after everything has been imported (because unresolved nodes are deleted at the beginning of AD Miner run). In other words AVOID doing like ingest 1 domain, run AD Miner, then ingest an additional domain and rerun AD Miner.

Again, happy to discuss this in a more interactive fashion on Discord server (see link in the README)
